name: example-cron
on:
  schedule:
    # runs tests every day at 4am
    - cron: '0 4 * * *'
jobs:
  nightly:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress nightly tests
        uses: cypress-io/github-action@v6
        with:
            working-directory: cypress/examples
            install-command: npm install
            build: npm run build
            start: npm start